name: Build Kernel with KernelSU Next
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Set up Build Environment
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf libelf-dev libssl-dev libxml2-utils lzop rsync zip libssl-dev python3 python-is-python3

    - name: Download KernelSU Next safely
      run: |
        rm -rf drivers/kernelsu drivers/KernelSU KernelSU
        mkdir -p drivers/kernelsu
        
        PART1="https://github.com"
        PART2="/KernelSU-Next/KernelSU-Next"
        PART3="/archive/refs/heads/dev.tar.gz"
        
        FULL_URL="${PART1}${PART2}${PART3}"
        curl -LSs "$FULL_URL" | tar -xz -C drivers/kernelsu --strip-components=1
        
        # حل مشکل تداخل مسیر فایل Kconfig اگزینوس
        if [ -f "drivers/kernelsu/kernel/Kconfig" ]; then
          cp drivers/kernelsu/kernel/Kconfig drivers/kernelsu/Kconfig
        fi
        
        # ایجاد لینک‌های مجازی دقیق در تمام مسیرهای احتمالی مورد نیاز Makefile
        ln -sf kernelsu drivers/KernelSU
        ln -sf drivers/kernelsu KernelSU

    - name: Build Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        chmod +x build_kernel.sh
        ./build_kernel.sh
        
    - name: Upload Kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: Kernel-Image-Exynos2100
        path: out/arch/arm64/boot/Image*
